variable = input("Input value: ")
print(f"The value {variable} is alpha? {variable.isalpha()}")
print(f"The value {variable} is numeric? {variable.isnumeric()}")
print(f"The value {variable} is alphanumeric? {variable.isalnum()}")
print(f"The value {variable} is space? {variable.isspace()}")
print(f"The value {variable} is printable? {variable.isprintable()}")
print(f"The value {variable} is decimal? {variable.isdecimal()}")
print(f"The value {variable} is num? {variable.isalnum()}")
print(f"The value {variable} is is identifier? {variable.isidentifier()}")
print(f"The value {variable} is is ascii? {variable.isascii()}")
print(f"The value {variable} is is digit? {variable.isdigit()}")
print(variable)

input()